---
node_exporter_version: "latest"
node_exporter_bin_path: /usr/local/bin/node_exporter
node_exporter_user: node_exporter
node_exporter_group: node_exporter
node_exporter_textfile_dir: /var/lib/node_exporter/textfile_collector
node_exporter_service_path: /etc/systemd/system/node_exporter.service
